// <auto-generated />
using System;
using ElevatorApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElevatorApi.Migrations
{
    [DbContext(typeof(ElevatorDbContext))]
    [Migration("20250721092028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elevator.Api.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Elevator.Api.Entities.Elevator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentFloor")
                        .HasColumnType("int");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("DoorStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId")
                        .IsUnique();

                    b.ToTable("Elevators");
                });

            modelBuilder.Entity("Elevator.Api.Entities.ElevatorCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CallTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DestinationFloor")
                        .HasColumnType("int");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("bit");

                    b.Property<int>("RequestedFloor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("ElevatorCalls");
                });

            modelBuilder.Entity("Elevator.Api.Entities.ElevatorCallAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignmentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElevatorCallId")
                        .HasColumnType("int");

                    b.Property<int>("ElevatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElevatorCallId");

                    b.HasIndex("ElevatorId");

                    b.ToTable("ElevatorCallAssignments");
                });

            modelBuilder.Entity("Elevator.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Elevator.Api.Entities.Building", b =>
                {
                    b.HasOne("Elevator.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Elevator.Api.Entities.Elevator", b =>
                {
                    b.HasOne("Elevator.Api.Entities.Building", "Building")
                        .WithOne("Elevator")
                        .HasForeignKey("Elevator.Api.Entities.Elevator", "BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Elevator.Api.Entities.ElevatorCall", b =>
                {
                    b.HasOne("Elevator.Api.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Elevator.Api.Entities.ElevatorCallAssignment", b =>
                {
                    b.HasOne("Elevator.Api.Entities.ElevatorCall", "ElevatorCall")
                        .WithMany("ElevatorCallAssignments")
                        .HasForeignKey("ElevatorCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elevator.Api.Entities.Elevator", "Elevator")
                        .WithMany("ElevatorCallAssignments")
                        .HasForeignKey("ElevatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Elevator");

                    b.Navigation("ElevatorCall");
                });

            modelBuilder.Entity("Elevator.Api.Entities.Building", b =>
                {
                    b.Navigation("Elevator")
                        .IsRequired();
                });

            modelBuilder.Entity("Elevator.Api.Entities.Elevator", b =>
                {
                    b.Navigation("ElevatorCallAssignments");
                });

            modelBuilder.Entity("Elevator.Api.Entities.ElevatorCall", b =>
                {
                    b.Navigation("ElevatorCallAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
